### ISSUE TITLE
"Print when" page on "Field properties" dialog shows duplicated group in combobox

### ISSUE THREAD

**Issue by MJindrova** [VFPX/ReportingApps#6]
Class Panelprintwhen, method  LoadFromFRX() - this method calls twice. This bug is related with fixed bug in Pgfhandlerframe::Click() event in frxcontrols.vcx.

```
*Panelprintwhen::LoadFromFRX()

THIS.group.Clear() && MJ 2022-04-12
scan
  THIS.group.AddItem(EXPR)
endscan
```

**Comment by DougHennig** [comment]
Thanks, Martina.
