### ISSUE TITLE
Print when problem

### ISSUE THREAD

**Issue by creacionesintegrales** [VFPX/ReportingApps#7]
If I put an expression in the Print When of the object in Report, its OK.

But I put an expression in the Print When of a group of objects in Report, maxlenght of expression is 50.

I use VFPA but this problem exist in VFP9.

I consulted with Chen (VFPA creator) and he suggested I review the method panelmultiprop.loadfromfrx() in frxbuilder2.vcx

I changed

create cursor (m.cAlias) ( ;
    PROP_ENABLE  l, ;
    PROP_NAME     c(50), ;
    PROP_VALUE   c(50), ;
    PROP_TYPE     i, ;
    PROP_ID      i )

with

create cursor (m.cAlias) ( ;
    PROP_ENABLE  l, ;
    PROP_NAME     c(50), ;
    PROP_VALUE   c(**250**), ;
    PROP_TYPE     i, ;
    PROP_ID      i )

Also modify the anchor of panelmultiprop. Its value was 0 and now is 15.

**Comment by DougHennig** [comment]
Thanks for the details. I implemented these changes.
